repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.1
    hooks:
    -   id: ruff
-   repo: https://github.com/try-ty/ty-pre-commit
    rev: v0.0.1a14
    hooks:
    -   id: ty
