project:
  type: website
  output-dir: _site

website:
  title: "weightedstate"
  sidebar:
    - title: "weightedstate"
      style: "docked"
      contents:
        - href: index.qmd
          text: "Get started"
        - href: estimation.qmd
          text: "Estimation framework"
        - href: examples.qmd
          text: "Examples"
        - href: literature.qmd
          text: "Relation to literature"
        - href: references.qmd
          text: "References"
        - text: "---"
        - section: "API Reference"
          contents:
            - reference/index.qmd
            - reference/weightedstate.qmd

format:
  html:
    theme:
      light: cosmo
    css: custom.scss

quartodoc:
  package: weightedstate
  sections:
    - title: "Core Functions"
      desc: "Functions for weighted event prediction."
      contents:
        - survival.weighted_aalen_johansen
