project:
  type: website
  output-dir: _site

website:
  title: "weightedstate"
  sidebar:
    - id: "reference"
      title: "API Reference"
      style: "docked"
      contents:
        - "reference/index.qmd"
        - "reference/weightedstate.qmd"

quartodoc:
  package: weightedstate
  sections:
    - title: "Core Functions"
      desc: "Functions for weighted event prediction."
      contents:
        - weightedstate.survival.weighted_aalen_johansen
